@include('admin.general.header')
@include('admin.general.menu')
@include('admin.general.top-nav')
@yield('content')            
@include('admin.general.notify')             
@include('admin.general.footer')             